#!/bin/sh

# This file should go to /etc/init.d/ directory on the device's SD card

# User startup script

# Uncomment the following and set a proper <DNS_IP> if your
# network configuration is static.
# echo "nameserver <DNS_IP>" > /tmp/resolv.conf

echo "Feel free to add custom initialization commands here."

ln -s /opt/usr/bin/python /usr/bin/python
ln -s /opt/usr/bin/ipython /usr/bin/ipython
ln -s /opt/usr/lib/libmonitor.so /usr/lib

# start RPyC server
( /opt/bin/rpyc_server > /dev/null ) &